### ISSUE TITLE
Upon running the code, I stumble upon a problem wherein it is supposed to add 1 minute after every 59 seconds but it adds 2 minutes

### ISSUE THREAD

**Issue by JhonPaul1019** [JhonPaul1019/midterm-exam#17]

**Comment by JhonPaul1019** [comment]
it is supposed to add 1 minute after every 59 seconds but it adds 2 minutes and in the hours also.. Needed to be fixed asap..

**Comment by GridenTagalog123** [comment]
Fixed bug issue #17
Now it add 1 minute after every 59 seconds and in the hours also.

Commit ID: d8c47b32e067e9f87246eb72a1dd235587d0413f

**Comment by JhonPaul1019** [comment]
Thanksss..
